import {appSchema, tableSchema} from '@nozbe/watermelondb';

export default appSchema({
  version: 7,
  tables: [
    tableSchema({
      name: 'items',
      columns: [
        {name: 'local_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'cloud_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'user_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'name', type: 'string'},
        {name: 'barcode', type: 'string', isOptional: true},
        {name: 'sku', type: 'string', isOptional: true},
        {name: 'price', type: 'number'},
        {name: 'unit', type: 'string'},
        {name: 'image_path', type: 'string', isOptional: true},
        {name: 'category', type: 'string', isOptional: true},
        {name: 'recommended', type: 'boolean'},
        {name: 'default_quantity', type: 'number'},
        {name: 'inventory_qty', type: 'number', isOptional: true},
        {name: 'is_synced', type: 'boolean', isOptional: true},
        {name: 'sync_status', type: 'string', isOptional: true},
        {name: 'sync_error', type: 'string', isOptional: true},
        {name: 'last_sync_attempt', type: 'string', isOptional: true},
        {name: 'synced_at', type: 'string', isOptional: true},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
        {name: 'idempotency_key', type: 'string', isOptional: true, isIndexed: true},
      ],
    }),
    tableSchema({
      name: 'customers',
      columns: [
        {name: 'local_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'cloud_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'user_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'name', type: 'string'},
        {name: 'phone', type: 'string', isOptional: true},
        {name: 'email', type: 'string', isOptional: true},
        {name: 'address', type: 'string', isOptional: true},
        {name: 'is_synced', type: 'boolean', isOptional: true},
        {name: 'sync_status', type: 'string', isOptional: true},
        {name: 'sync_error', type: 'string', isOptional: true},
        {name: 'last_sync_attempt', type: 'string', isOptional: true},
        {name: 'synced_at', type: 'string', isOptional: true},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
        {name: 'idempotency_key', type: 'string', isOptional: true, isIndexed: true},
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        {name: 'local_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'cloud_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'user_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'voucher_number', type: 'string', isOptional: true, isIndexed: true},
        {name: 'provisional_voucher', type: 'string', isOptional: true},
        {name: 'customer_id', type: 'string', isOptional: true},
        {name: 'customer_name', type: 'string', isOptional: true},
        {name: 'customer_mobile', type: 'string', isOptional: true},
        {name: 'date', type: 'string'},
        {name: 'subtotal', type: 'number'},
        {name: 'tax', type: 'number'},
        {name: 'discount', type: 'number'},
        {name: 'other_charges', type: 'number'},
        {name: 'grand_total', type: 'number'},
        {name: 'item_count', type: 'number'},
        {name: 'unit_count', type: 'number'},
        {name: 'payment_type', type: 'string', isOptional: true},
        {name: 'status', type: 'string'},
        {name: 'receipt_file_path', type: 'string', isOptional: true},
        {name: 'is_synced', type: 'boolean', isOptional: true},
        {name: 'sync_status', type: 'string', isOptional: true},
        {name: 'sync_error', type: 'string', isOptional: true},
        {name: 'last_sync_attempt', type: 'string', isOptional: true},
        {name: 'synced_at', type: 'string', isOptional: true},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
        {name: 'idempotency_key', type: 'string', isOptional: true, isIndexed: true},
      ],
    }),
    tableSchema({
      name: 'transaction_lines',
      columns: [
        {name: 'local_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'cloud_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'user_id', type: 'string', isOptional: true, isIndexed: true},
        {name: 'transaction_id', type: 'string', isIndexed: true},
        {name: 'item_id', type: 'string', isIndexed: true},
        {name: 'item_name', type: 'string'},
        {name: 'quantity', type: 'number'},
        {name: 'unit_price', type: 'number'},
        {name: 'per_line_discount', type: 'number'},
        {name: 'line_total', type: 'number'},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
        {name: 'idempotency_key', type: 'string', isOptional: true, isIndexed: true},
      ],
    }),
    tableSchema({
      name: 'settings',
      columns: [
        {name: 'key', type: 'string', isIndexed: true},
        {name: 'value', type: 'string'},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'audit_logs',
      columns: [
        {name: 'type', type: 'string'},
        {name: 'message', type: 'string'},
        {name: 'meta', type: 'string'},
        {name: 'timestamp', type: 'number'},
      ],
    }),
    tableSchema({
      name: 'sync_queue',
      columns: [
        {name: 'entity_type', type: 'string', isIndexed: true},
        {name: 'entity_id', type: 'string', isIndexed: true},
        {name: 'operation', type: 'string'},
        {name: 'data', type: 'string'},
        {name: 'retry_count', type: 'number'},
        {name: 'last_error', type: 'string', isOptional: true},
        {name: 'created_at', type: 'number'},
        {name: 'updated_at', type: 'number'},
      ],
    }),
  ],
});
