export const seedItems = [
  {
    name: 'Sugar 1kg',
    barcode: '8901234567890',
    price: 60,
    unit: 'kg',
    category: 'Grocery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Tea Powder 250g',
    barcode: '8901234567891',
    price: 80,
    unit: 'gm',
    category: 'Grocery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Biscuit 200g',
    barcode: '8901234567892',
    price: 30,
    unit: 'gm',
    category: 'Snacks',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Poha 500g',
    barcode: '8901234567893',
    price: 20,
    unit: 'gm',
    category: 'Grocery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Bread',
    barcode: '8901234567894',
    price: 40,
    unit: 'piece',
    category: 'Bakery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Cooking Oil 1L',
    barcode: '8901234567895',
    price: 120,
    unit: 'ltr',
    category: 'Grocery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Salt 1kg',
    barcode: '8901234567896',
    price: 25,
    unit: 'kg',
    category: 'Grocery',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Toothpaste',
    barcode: '8901234567897',
    price: 60,
    unit: 'piece',
    category: 'Personal Care',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Shampoo 200ml',
    barcode: '8901234567898',
    price: 45,
    unit: 'ml',
    category: 'Personal Care',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Detergent 1kg',
    barcode: '8901234567899',
    price: 100,
    unit: 'kg',
    category: 'Household',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Soap',
    barcode: '8901234567900',
    price: 25,
    unit: 'piece',
    category: 'Personal Care',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Jam 500g',
    barcode: '8901234567901',
    price: 90,
    unit: 'gm',
    category: 'Spreads',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Ghee 500g',
    barcode: '8901234567902',
    price: 110,
    unit: 'gm',
    category: 'Dairy',
    recommended: true,
    defaultQuantity: 1,
  },
  {
    name: 'Milk 1L',
    barcode: '8901234567903',
    price: 60,
    unit: 'ltr',
    category: 'Dairy',
    recommended: false,
    defaultQuantity: 1,
  },
  {
    name: 'Rice 5kg',
    barcode: '8901234567904',
    price: 250,
    unit: 'kg',
    category: 'Grocery',
    recommended: false,
    defaultQuantity: 1,
  },
];

export const defaultSettings = [
  {key: 'currencySymbol', value: '₹'},
  {key: 'exportFolderPath', value: 'Documents/GuruReceipts'},
  {key: 'privacyMode', value: 'strict'},
  {key: 'taxDefaultPercent', value: '0'},
  {key: 'EnableCloudAuth', value: 'true'},
  {key: 'developerShareToggle', value: 'false'},
  {key: 'useEncryptedDB', value: 'false'},
];
